### ISSUE TITLE
Display Verbose Stream when Jobs are Received

### ISSUE THREAD

**Issue by ryan-leap** [proxb/PoshRSJob#47] opened 2015-10-28 18:30 UTC
Would it be possible to display verbose stream (when Write-Verbose is used in the script block being executed within a job) messages when RSJobs are received?  Traditional PSJobs do display the verbose stream if the $VerbosePreference variable is set to something other than SilentlyContinue within the script block but I'm not seeing verbose output with RSJobs.

**Comment by proxb** [comment] 2015-11-24 02:59
Can you put together some demo code showing this so I can look at and then work to see if I can make a fix for this?

**Comment by proxb** [comment] 2015-12-07 01:19
Duplicate of #20

**Closed** 2016-01-08 19:13 UTC
Labels: duplicate, enhancement
