### ISSUE TITLE
Wait-RsJob -State Completed with no input returns Attempted to divide by zero.

### ISSUE THREAD

**Issue by codykonior** [proxb/PoshRSJob#101] opened 2016-09-20 01:40 UTC
```
PS C:\Windows\system32> Import-Module PoshRSJob

PS C:\Windows\system32> Wait-RSJob -State Completed
Attempted to divide by zero.
At C:\...\PowerShell\Modules\poshrsjob\Public\Wait-RSJob.ps1:180 char:42
+                 Write-Verbose "Status: $($Completed/$TotalJobs)"
+                                          ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException
 

PS C:\Windows\system32> 
```

**Comment by proxb** [comment] 2016-09-20 02:31
Thanks for the heads up! I'll look to get this fixed up.

**Comment by proxb** [comment] 2016-09-26 01:38
What version of PoshRSJob are you running? Just curious as I thought this was fixed in a recent version and I cannot reproduce on the current version (1.7.2.6)

**Comment by codykonior** [comment] 2016-09-27 02:50
I was on 1.7.2.4 which is the copy I got on the 19th. 

Cody

**Comment by proxb** [comment] 2016-09-27 02:53
Ok. Try it with the latest version (1.7.2.7) and see if the issue is still happening.

**Comment by MVKozlov** [comment] 2016-09-27 08:18
```
PS C:\> Import-Module PoshRSJob
PS C:\> Get-Module PoshRSJob

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.7.2.7    PoshRSJob                           {Get-RSJob, Receive-RSJob, Remove-RSJob, Start-RSJob...}
PS C:\> Wait-RSJob -State Completed
Попытка деления на нуль.
At C:\USERS\MVKozlov\Documents\WindowsPowerShell\Modules\PoshRSJob\Public\Wait-RSJob.ps1:180 char:42
+                 Write-Verbose "Status: $($Completed/$TotalJobs)"
+                                          ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException
```

**Comment by proxb** [comment] 2016-09-27 11:13
Yep, I was looking at the wrong thing. This will be fixed in the next release.

**Closed** 2016-09-29 02:00 UTC
Labels: bug, Ready
