### ISSUE TITLE
Receive-RSJob doesn't clear a job's HasMoreData state

### ISSUE THREAD

**Issue by ALuckyGuy** [proxb/PoshRSJob#59] opened 2016-03-07 16:24 UTC
I've tried this on both PS v2 and v3 with the same result.

Both examples on the home page result in Completed jobs that show there is more data to retrieve even when there is not.  When a job is Completed and its last data has been fetched, HasMoreData should become False and then we know it can be removed. For instance, after running the second example, calling get-rsjob again shows the following:

```
PS > Get-RSjob

Id       Name                 State           HasMoreData  HasErrors    Command
--       ----                 -----           -----------  ---------    -------
36       Job36                Completed       True         False        ...
37       Job37                Completed       True         False        ...
38       Job38                Completed       True         False        ...
39       Job39                Completed       True         False        ...
40       Job40                Completed       True         False        ...
41       Job41                Completed       True         False        ...
42       Job42                Completed       True         False        ...
43       Job43                Completed       True         False        ...
44       Job44                Completed       True         False        ...
45       Job45                Completed       True         False        ...
```

With HasMoreData = True, we should be required to call receive-rsjob to receive the data, but doing so results in the same output as the original call to receive-rsjob. HasMoreData never becomes false.

Run a similar test with standard PS jobs and once a job's data is fetched, HasMoreData becomes False and a call to receive-job results in no additional data. 

Edit: fixed typos

**Comment by proxb** [comment] 2016-03-10 23:33
This is by design which does deviate from how the PSJobs are handled. Currently I have not found a good way to allow a streaming of data being outputted and can only return all of the results when the runspace has completed. The only exceptions to this are when using the Verbose, Warning, Error, Debug and Progress streams. If I (or someone else) can solve this issue with streaming output from a runspace, then I would definitely add that into PoshRSJob.

**Comment by ALuckyGuy** [comment] 2016-03-11 17:40
Thanks for the update. However, even if the job can't provide it's output until completed, it seems like it would be useful to have the HasMoreData flag get cleared when the data is read from a completed job, if possible.  Then the rsjob equivalent of code below would still work. 

    1..3 | %{ Start-Job -name $_ -ScriptBlock { 1..10 | %{ $_ ; Start-Sleep -Seconds 1 } }  }
    do { get-job -HasMoreData | wait-job | receive-job } 
    until ( get-job | ? { $_.state -eq 'Completed' -and -not $_.HasMoreData } ) 

The rsjob equivalent wouldn't return results as they were produced - jobs wouldn't produce results until they went to a Completed status - but then when the results were read, the loop would terminate. PoshRSJob would be more compatible with the standard job implementation and a virtual drop-in replacement.

As it is right now, the above produces an endless loop and one has to be more careful about result handling.

Just my two cents... thanks for the nice module!

**Comment by codykonior** [comment] 2016-08-29 03:04
I believe ALuckyGuy is correct.  Here's a test.

(Get-RSJob | Remove-RSJob); [void] (Start-RSJob -ScriptBlock { Get-ChildItem }); Start-Sleep -Seconds 1; [void] (Get-RSJob | Receive-RSJob); Get-RSJob | Where { $_.HasMoreData }

Clear jobs. Start a job. Get the output. Even though it's complete and the data has been received the HasMoreData flag is still set.

**Comment by proxb** [comment] 2016-08-29 11:34
I really should have named that property HasData instead of HasMoreData as it gives a false impression that more data might exist after initially running Receive-RSJob. I blame that on wanting this to closely mirror the PSJob cmdlets.

**Comment by proxb** [comment] 2016-08-30 00:35
Fixed with latest PR https://github.com/proxb/PoshRSJob/pull/89

**Closed by proxb** 2016-08-30 00:35 UTC
Labels: enhancement, help wanted
